config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  devise_for :users

  resources :articles do
    member do
      get "like", to: "articles#upvote"
      get "dislike", to: "articles#downvote"
    end
    resources :comments
  end


end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_votable

  # associations
  belongs_to :user
  has_many :comments

  # validation
  validates_presence_of :title, :content, :link

  # paperclip
  has_attached_file :image, styles:{ large: "600x600>",
                                    medium: "300x300>",
                                     small: "150x150#" },
   url: "/assets/:class/:id/:style.:extension",
   path: ":rails_root/public/assets/:class/:id/:style.:extension"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_presence :image
  validates_attachment_file_name :image, matches: [/png\Z/, /jpe?g/]
  validates_attachment_size :image, less_than: 3.megabytes
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  # associations
  belongs_to :article
  belongs_to :user

  # validations
  validates_presence_of :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # asscociations
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :find_user, only: [:new, :create, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all.order("created_at DESC")
  end

  def show
    @comments = Comment.where(article_id: @article)
  end

  def new
    @article = @user.articles.build
  end

  def edit
  end

  def create
    @article = @user.articles.build(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end


  def upvote
    @article.upvote_by @user
    redirect_to :back
  end

  def downvote
    @article.downvote_by @user
    redirect_to :back
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def find_user
    @user = current_user
  end

  def article_params
    params.require(:article).permit(:title, :content, :link, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @user = current_user
    @article = Article.find(params[:article_id])
    @comment = Comment.create(comments_params)
    @comment.user_id = @user.id
    @comment.article_id = @article.id

    if @comment.save
      redirect_to article_path(@article), notice: "Thank you for comment!"
    else
      redirect_to article_path(@article), notice: "You didn't write any comments!"
    end
  end

  private
  def comments_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.haml
= simple_form_for @article html: { multipsrt: true } do |form|
  = form.input :image
  = form.input :title
  = form.input :content, as: :text
  = form.input :link
  = form.button :submit

app/views/articles/edit.html.haml
%h2 Edit Article
= render "form"

app/views/articles/index.html.haml
- if user_signed_in?
  %p#intro
    Hello
    = current_user.name.capitalize
    %br/
    %span
      Share your stickers and art here!
- else
  %p#intro
    What is your mood?
    %br/
    %span
      Share your stickers and art here!

#posts
  - @articles.each do |article|
    .post
      .post_image
        = link_to image_tag(article.image.url(:small)), article
      .post_content
        .title
          %h2= link_to article.title, article
        .data.clearfix
          %p.username
            Shared By:
            = article.user.name
          %p.buttons
            %span
              %i.fa.af-comments-o
              = article.comments.count
              %i.fa.af-thumbs-up
              = article.get_likes.size
  =link_to "New Article", new_article_path

app/views/articles/new.html.haml
%h2 New Article
= render "form"

app/views/articles/show.html.haml
#post_show
  %h1= @article.title
  %p.username
    Share by:
    = @article.user.name
    about
    = time_ago_in_words(@article.created_at)
  .clearfix
    .post_image_description
      = image_tag @article.image.url(:medium)
      .description= simple_format(@article.content)
    .post_date
      = link_to "Visit Link", @article.link, class: "button"

      = link_to like_article_path(@article), method: :get, class: "data" do
        %i.fa.fa-thumbs-o-up
        = pluralize(@article.get_upvotes.size, "Like")

      = link_to like_article_path(@article), method: :get, class: "data" do
        %i.fa.fa-thumbs-o-down
        = pluralize(@article.get_downvotes.size, "Dislike")
      %p.data
        %i.fa.fa-comments-o
        = pluralize(@article.comments.count, "Comment")
      - if @article.user == current_user
        = link_to "Edit", edit_article_path(@article), class: "data"
        = link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "data"

    #comments
      %h2
      - @comments.each do |comment|
        %p= comment.body
        %p= comment.user.name

      %h3 Reply to thread
      = render "comments/form"

app/views/comments/_comment.html.haml
%p= @comment.body
%p= @comment.user.name

app/views/comments/_form.html.haml
= simple_form_for([@article, @article.comments.build]) do |f|
  = f.input :body, label: false
  = f.button :submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Stickers
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %link{ rel: "stylesheet", href: "https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.2/normalize.css"}
    %link{ rel: "stylesheet", href: "//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"}
    = csrf_meta_tags
  %body
    %header
      .wrapper.clearfix
        #logo= link_to "Stickers", root_path
        %nav
          - if user_signed_in?
            = link_to current_user.name, edit_user_registration_path
            = link_to "Sign out", destroy_user_session_path
            = link_to "Add New Stickers", new_article_path, class: "button"
          - else
            = link_to "Sign up", new_user_registration_path, class: "button"
            = link_to "Sign in", new_user_session_path, class: "button"

    %p.notice= notice
    %p.alert= alert
    = yield